# Generated by Django 5.1.4 on 2024-12-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='description',
            new_name='category',
        ),
    ]
